#Requires AutoHotkey v2.0

Global LangMap := Map()

InitLang() {
    Global LangMap
    
    ; --- ENGLISH ---
    LangMap["EN"] := Map(
        "TutTitle", "Welcome to FoxPath!",
        "TutSubtitle", "Your new mascot is ready to help you manage files and paths like a true power-user!",
        "TutHowTo", "How it Works",
        "TutHowToDesc", "Press the shortcut  [ {1} ]  to summon the fox.`nSelect a file or folder in File Explorer.",
        "TutInteract", "Interaction & Menu",
        "TutInteractDesc", "• Left Click: Quick copy to Clipboard.`n• Right Click: Access Quick Actions, Text Extraction (OCR), Developer Menu and Filters.",
        "TutCust", "Customization",
        "TutCustDesc", "Click the gear icon (or choose the option from the menu) to customize Hotkeys and appearance.",
        "TutOptStart", " Start FoxPath automatically with Windows",
        "TutOptDesk", " Create a shortcut on the Desktop",
        "TutBtnStart", "Start using FoxPath ➔",
        "TutCopyright", "© 2026 Pedro Sanchez.`nAll rights reserved.",
        "Lang", "Language",
        "SettingsTitle", "FoxPath Settings",
        "TabAppearance", "🎨 Appearance",
        "TabBehavior", "⚙️ Behavior",
        "TabTools", "🛠️ Tools",
        "VisualCust", "Visual Customization",
        "Transp", "Transparency ({1}/255):",
        "WinWidth", "Window Width ({1}px):",
        "PanelHeight", "Info Panel Height ({1}px):",
        "BtnColor", "Button Color:",
        "TxtColor", "Text Color:",
        "Palette", "Palette",
        "InteractOpt", "Interaction Options",
        "MultiSel", "Enable Multiple Selection",
        "UnlockResize", "Unlock Manual Resize",
        "PlaySound", "Play Sound on Copy",
        "AutoHide", "Auto-hide Fox after copy",
        "AutoStart", "Start automatically with Windows",
        "GlobalShortcut", "Global Keyboard Shortcut:",
        "PrimaryTool", "Primary Tool",
        "PrimaryAction", "Default Action on Left Click:",
        "QuickMenu", "Quick Menu (Right Click)",
        "Slot", "Slot {1}:",
        "SaveApply", "✔️ Save and Apply",
        "Reset", "🔄 Reset",
        "Info", "ℹ️ About FoxPath",
        "InfoMsg", "FoxPath v2.1.0`n`nYour visual assistant for Windows productivity.`n`n© 2026 Pedro Sanchez. All rights reserved.",
        "SettingsLang", "App Language:",
        "NoSel", "NO SELECTION",
        "Detected", "DETECTED",
        "ClickFile", "click on a file",
        
        "Nessuno", "None",
        "📋 ─── LIBRERIA COPIA E FORMATTAZIONE ───", "📋 ─── COPY & FORMATTING LIBRARY ───",
        "Copia Percorso Normale", "Copy Normal Path",
        "Copia come File Reali", "Copy as Real Files",
        "Copia tra Virgolette", "Copy with Quotes",
        "Copia come Link Markdown", "Copy as Markdown Link",
        "🖥️ ─── LIBRERIA PROGRAMMI E SISTEMA ───", "🖥️ ─── SYSTEM & PROGRAMS LIBRARY ───",
        "Apri in VS Code", "Open in VS Code",
        "Apri in PowerShell", "Open in PowerShell",
        "Rinomina Elemento", "Rename Item",
        "Formatta JSON", "Format JSON (Pretty Print)",
        "Minifica JSON", "Minify JSON",
        "✍️ ─── LIBRERIA ESTRAZIONE E TESTO ───", "✍️ ─── EXTRACTION & TEXT LIBRARY ───",
        "Copia Contenuto (Solo Testo)", "Copy Content (Text Only)",
        "Copia Contenuto (Mantiene Formattazione)", "Copy Content (Keep Formatting)",
        "Statistiche Testo", "Text Statistics",
        "Traduci in Google Translate", "Translate in Google Translate",
        "Incolla Appunti Veloci", "Paste Quick Notes",
        "📸 ─── LIBRERIA IMMAGINI E GRAFICA ───", "📸 ─── IMAGES & GRAPHICS LIBRARY ───",
        "Estrai Testo (OCR)", "Extract Text (OCR)",
        "Converti in PNG", "Convert to PNG",
        "Converti in JPG", "Convert to JPG",
        "Converti in BMP", "Convert to BMP",
        "Estrai Palette Colori", "Extract Color Palette",
        "🛠️ ─── LIBRERIA UTILITÀ EXTRA ───", "🛠️ ─── EXTRA UTILITIES LIBRARY ───",
        "Touch (Aggiorna Data)", "Touch (Update Date)",
        "Distruzione Sicura", "Secure Shred",
        "Crea Collegamento", "Create Shortcut",
        "Super Zip (Unico)", "Super Zip (Single Archive)",
        "Super Zip (Separati)", "Super Zip (Separate Archives)",
        "Svuota Cestino", "Empty Recycle Bin",
        
        "Copia separati da Virgola", "Copy separated by Comma",
        "Copia con Slash ( / )", "Copy with Slash ( / )",
        "Copia Relativo (senza Unità)", "Copy Relative (no Drive)",
        "Formattazione Avanzata", "✨ Advanced Formatting",
        "Copia solo Nome File", "Copy File Name Only",
        "Copia Cartella Padre", "Copy Parent Folder",
        "Copia Contenuto del File", "📝 Copy File Content",
        "Singolo File", "Single File",
        "Azioni Rapide", "Quick Actions",
        "Recenti (History)", "Recent (History)",
        "Impostazioni", "⚙️ Settings...",
        "⚙️ Impostazioni...", "⚙️ Settings...",
        "Copia come Web URI (file:///)", "Copy as Web URI (file:///)",
        "Copia come Array JSON", "Copy as JSON Array",
        "Copia come Percorso WSL (/mnt/...)", "Copy as WSL Path (/mnt/...)",
        "📝 Copia Contenuto (Solo Testo)", "📝 Copy Content (Text Only)",
        "✨ Formatta JSON (Pretty Print)", "✨ Format JSON (Pretty Print)",
        "🗜️ Minifica JSON", "🗜️ Minify JSON",
        "📄 Testo & Codice", "📄 Text & Code",
        "📝 Copia Contenuto (Mantiene Formattazione)", "📝 Copy Content (Keep Formatting)",
        "📝 Copia Contenuto (Solo Testo Grezzo)", "📝 Copy Content (Raw Text Only)",
        "📄 Esporta in PDF (Silenzioso)", "📄 Export to PDF (Silent)",
        "📄 Strumenti Office", "📄 Office Tools",
        "🔍 Anteprima Dati (Head)", "🔍 Data Preview (Head)",
        "🔄 Converti in JSON", "🔄 Convert to JSON",
        "📊 Dati & File Log", "📊 Data & Log Files",
        "📈 Statistiche Testo (Parole/Caratteri)", "📈 Text Statistics (Words/Chars)",
        "🌐 Traduci in Google Translate", "🌐 Translate in Google Translate",
        "🔗 Copia come Link Markdown", "🔗 Copy as Markdown Link",
        "✍️ Editoriale", "✍️ Editorial",
        "✂️ Copia SVG Minimizzato", "✂️ Copy Minified SVG",
        "🔍 Estrai Testo (OCR)", "🔍 Extract Text (OCR)",
        "📐 Ridimensiona (Smart Resize)...", "📐 Resize (Smart Resize)...",
        "🖼️ Genera Icona (.ico)", "🖼️ Generate Icon (.ico)",
        "🔄 Converti in PNG", "🔄 Convert to PNG",
        "🔄 Converti in JPG", "🔄 Convert to JPG",
        "🔄 Converti in BMP", "🔄 Convert to BMP",
        "🎨 Estrai Palette (Colori Dominanti)", "🎨 Extract Palette (Dominant Colors)",
        "📸 Immagini & Grafica", "📸 Images & Graphics",
        "🔐 Calcola Checksum (MD5/SHA-256)", "🔐 Calculate Checksum (MD5/SHA-256)",
        "🌐 URL Encode / Decode...", "🌐 URL Encode / Decode...",
        "️ Copia come Base64", "️ Copy as Base64",
        "🔑 JWT Decoder (Da Appunti)", "🔑 JWT Decoder (From Clipboard)",
        "🧪 Test RegEx Rapido...", "🧪 Quick RegEx Test...",
        "📸 Copia Metadati (JSON)", "📸 Copy Metadata (JSON)",
        "🧬 Estrai Stringhe (Text)", "🧬 Extract Strings (Text)",
        "🗜️ Aumenta Peso File (Pumper)...", "🗜️ Increase File Size (Pumper)...",
        "🗑️ Distruzione Sicura", "🗑️ Secure Shred",
        "🛠️ Sviluppatore & Sicurezza", "🛠️ Developer & Security",
        "🧩 Crea File da Appunti (Decodifica Base64)", "🧩 Create File from Clipboard (Base64 Decode)",
        "🗜️ Crea File Dummy (Zero Fill)...", "🗜️ Create Dummy File (Zero Fill)...",
        "🔗 Crea Symlink (Target da Appunti)", "🔗 Create Symlink (Target from Clipboard)",
        "🛠️ Sviluppatore", "🛠️ Developer",
        "⬇️ Git Pull", "⬇️ Git Pull",
        "✅ Git Add & Commit...", "✅ Git Add & Commit...",
        "📄 Crea File da Snippet...", "📄 Create File from Snippet...",
        "Git Actions", "Git Actions",
        "💻 Programmazione", "💻 Programming",
        "📝 Incolla Appunti Veloci (.txt)", "📝 Paste Quick Notes (.txt)",
        "⚙️ Esegui con Parametri", "⚙️ Run with Arguments",
        "⏱️ Aggiorna Data Modifica (Touch)", "⏱️ Update Modification Date (Touch)",
        "🕰️ Modifica Attributi e Date...", "🕰️ Edit Attributes & Dates...",
        "✏️ Rinomina Elemento...", "✏️ Rename Item...",
        "🔗 Crea Collegamento...", "🔗 Create Shortcut...",
        "🖥️ Apri in PowerShell", "🖥️ Open in PowerShell",
        " Apri in VS Code", " Open in VS Code",
        "🔧 Gestione & Azioni", "🔧 Management & Actions",
        "🗃️ Rinomina Multipla...", "🗃️ Bulk Rename...",
        " Fast Merge (Unione Dati/Testi)", " Fast Merge (Merge Data/Text)",
        "🔗 Crea Collegamenti...", "🔗 Create Shortcuts...",
        " Gestione & Azioni", " Management & Actions",
        "🗜️ Comprimi in archivi separati (.zip)", "🗜️ Compress to separate archives (.zip)",
        "🗜️ Comprimi in un unico archivio (.zip)", "🗜️ Compress to single archive (.zip)",
        "📦 Super Zip", "📦 Super Zip",
        "Tutti in", "All in",
        "Solo i .", "Only .",
        "Immagini", "Images",
        "Sviluppo", "Development",
        "Documenti", "Documents",
        "Archivi", "Archives",
        "🔍 Filtra e Copia Percorsi...", "🔍 Filter & Copy Paths...",
        "📁 Filtra e Copia FILE reali...", "📁 Filter & Copy Real FILES..."
    )

    ; --- ITALIANO ---
    LangMap["IT"] := Map(
        "TutTitle", "Benvenuto in FoxPath!",
        "TutSubtitle", "La tua nuova mascotte è pronta ad aiutarti a gestire file e percorsi come un vero power-user!",
        "TutHowTo", "Come Funziona",
        "TutHowToDesc", "Premi la scorciatoia  [ {1} ]  per evocare la volpe.`nSeleziona un file o una cartella in Esplora File.",
        "TutInteract", "Interazione e Menu",
        "TutInteractDesc", "• Tasto Sinistro: Copia rapida negli Appunti.`n• Tasto Destro: Accedi alle Azioni Rapide, Estrazione Testi (OCR), Menu Sviluppatore e Filtri.",
        "TutCust", "Personalizzazione",
        "TutCustDesc", "Clicca sull'ingranaggio (o scegli l'opzione dal menu) per personalizzare i Tasti Rapidi e l'aspetto.",
        "TutOptStart", " Avvia FoxPath automaticamente all'accensione di Windows",
        "TutOptDesk", " Crea un collegamento rapido sul Desktop",
        "TutBtnStart", "Inizia a usare FoxPath ➔",
        "TutCopyright", "© 2026 Pedro Sanchez.`nTutti i diritti riservati.",
        "Lang", "Lingua",
        "SettingsTitle", "Impostazioni FoxPath",
        "TabAppearance", "🎨 Aspetto",
        "TabBehavior", "⚙️ Comportamento",
        "TabTools", "🛠️ Strumenti",
        "VisualCust", "Personalizzazione Visiva",
        "Transp", "Trasparenza ({1}/255):",
        "WinWidth", "Larghezza Finestra ({1}px):",
        "PanelHeight", "Altezza Pannello Info ({1}px):",
        "BtnColor", "Colore Bottone:",
        "TxtColor", "Colore Testo:",
        "Palette", "Palette",
        "InteractOpt", "Opzioni di Interazione",
        "MultiSel", "Abilita Selezione Multipla",
        "UnlockResize", "Sblocca Ridimensionamento Manuale",
        "PlaySound", "Riproduci Suono alla Copia",
        "AutoHide", "Nascondi automaticamente la Volpe",
        "AutoStart", "Avvia in automatico con Windows",
        "GlobalShortcut", "Scorciatoia Tastiera Globale:",
        "PrimaryTool", "Strumento Principale",
        "PrimaryAction", "Azione predefinita al Clic Sinistro:",
        "QuickMenu", "Menu Rapido (Tasto Destro)",
        "Slot", "Slot {1}:",
        "SaveApply", "✔️ Salva e Applica",
        "Reset", "🔄 Reset",
        "Info", "ℹ️ Informazioni su FoxPath",
        "InfoMsg", "FoxPath v2.1.0`n`nIl tuo assistente visivo per la produttività su Windows.`n`n© 2026 Pedro Sanchez. Tutti i diritti riservati.",
        "SettingsLang", "Lingua App:",
        "NoSel", "NESSUNA SEL.",
        "Detected", "RILEVATO",
        "ClickFile", "clicca su un file",
        
        "Nessuno", "Nessuno",
        "📋 ─── LIBRERIA COPIA E FORMATTAZIONE ───", "📋 ─── LIBRERIA COPIA E FORMATTAZIONE ───",
        "Copia Percorso Normale", "Copia Percorso Normale",
        "Copia come File Reali", "Copia come File Reali",
        "Copia tra Virgolette", "Copia tra Virgolette",
        "Copia come Link Markdown", "Copia come Link Markdown",
        "🖥️ ─── LIBRERIA PROGRAMMI E SISTEMA ───", "🖥️ ─── LIBRERIA PROGRAMMI E SISTEMA ───",
        "Apri in VS Code", "Apri in VS Code",
        "Apri in PowerShell", "Apri in PowerShell",
        "Rinomina Elemento", "Rinomina Elemento",
        "Formatta JSON", "Formatta JSON (Pretty Print)",
        "Minifica JSON", "Minifica JSON",
        "✍️ ─── LIBRERIA ESTRAZIONE E TESTO ───", "✍️ ─── LIBRERIA ESTRAZIONE E TESTO ───",
        "Copia Contenuto (Solo Testo)", "Copia Contenuto (Solo Testo)",
        "Copia Contenuto (Mantiene Formattazione)", "Copia Contenuto (Mantiene Formattazione)",
        "Statistiche Testo", "Statistiche Testo",
        "Traduci in Google Translate", "Traduci in Google Translate",
        "Incolla Appunti Veloci", "Incolla Appunti Veloci",
        "📸 ─── LIBRERIA IMMAGINI E GRAFICA ───", "📸 ─── LIBRERIA IMMAGINI E GRAFICA ───",
        "Estrai Testo (OCR)", "Estrai Testo (OCR)",
        "Converti in PNG", "Converti in PNG",
        "Converti in JPG", "Converti in JPG",
        "Converti in BMP", "Converti in BMP",
        "Estrai Palette Colori", "Estrai Palette Colori",
        "🛠️ ─── LIBRERIA UTILITÀ EXTRA ───", "🛠️ ─── LIBRERIA UTILITÀ EXTRA ───",
        "Touch (Aggiorna Data)", "Touch (Aggiorna Data)",
        "Distruzione Sicura", "Distruzione Sicura",
        "Crea Collegamento", "Crea Collegamento",
        "Super Zip (Unico)", "Super Zip (Unico)",
        "Super Zip (Separati)", "Super Zip (Separati)",
        "Svuota Cestino", "Svuota Cestino",
        
        "Copia separati da Virgola", "Copia separati da Virgola",
        "Copia con Slash ( / )", "Copia con Slash ( / )",
        "Copia Relativo (senza Unità)", "Copia Relativo (senza Unità)",
        "Formattazione Avanzata", "✨ Formattazione Avanzata",
        "Copia solo Nome File", "Copia solo Nome File",
        "Copia Cartella Padre", "Copia Cartella Padre",
        "Copia Contenuto del File", "📝 Copia Contenuto del File",
        "Singolo File", "Singolo File",
        "Azioni Rapide", "Azioni Rapide",
        "Recenti (History)", "Recenti (History)",
        "Impostazioni", "⚙️ Impostazioni...",
        "⚙️ Impostazioni...", "⚙️ Impostazioni...",
        "Copia come Web URI (file:///)", "Copia come Web URI (file:///)",
        "Copia come Array JSON", "Copia come Array JSON",
        "Copia come Percorso WSL (/mnt/...)", "Copia come Percorso WSL (/mnt/...)",
        "📝 Copia Contenuto (Solo Testo)", "📝 Copia Contenuto (Solo Testo)",
        "✨ Formatta JSON (Pretty Print)", "✨ Formatta JSON (Pretty Print)",
        "🗜️ Minifica JSON", "🗜️ Minifica JSON",
        "📄 Testo & Codice", "📄 Testo & Codice",
        "📝 Copia Contenuto (Mantiene Formattazione)", "📝 Copia Contenuto (Mantiene Formattazione)",
        "📝 Copia Contenuto (Solo Testo Grezzo)", "📝 Copia Contenuto (Solo Testo Grezzo)",
        "📄 Esporta in PDF (Silenzioso)", "📄 Esporta in PDF (Silenzioso)",
        "📄 Strumenti Office", "📄 Strumenti Office",
        "🔍 Anteprima Dati (Head)", "🔍 Anteprima Dati (Head)",
        "🔄 Converti in JSON", "🔄 Converti in JSON",
        "📊 Dati & File Log", "📊 Dati & File Log",
        "📈 Statistiche Testo (Parole/Caratteri)", "📈 Statistiche Testo (Parole/Caratteri)",
        "🌐 Traduci in Google Translate", "🌐 Traduci in Google Translate",
        "🔗 Copia come Link Markdown", "🔗 Copia come Link Markdown",
        "✍️ Editoriale", "✍️ Editoriale",
        "✂️ Copia SVG Minimizzato", "✂️ Copia SVG Minimizzato",
        "🔍 Estrai Testo (OCR)", "🔍 Estrai Testo (OCR)",
        "📐 Ridimensiona (Smart Resize)...", "📐 Ridimensiona (Smart Resize)...",
        "🖼️ Genera Icona (.ico)", "🖼️ Genera Icona (.ico)",
        "🔄 Converti in PNG", "🔄 Converti in PNG",
        "🔄 Converti in JPG", "🔄 Converti in JPG",
        "🔄 Converti in BMP", "🔄 Converti in BMP",
        "🎨 Estrai Palette (Colori Dominanti)", "🎨 Estrai Palette (Colori Dominanti)",
        "📸 Immagini & Grafica", "📸 Immagini & Grafica",
        "🔐 Calcola Checksum (MD5/SHA-256)", "🔐 Calcola Checksum (MD5/SHA-256)",
        "🌐 URL Encode / Decode...", "🌐 URL Encode / Decode...",
        "️ Copia come Base64", "️ Copia come Base64",
        "🔑 JWT Decoder (Da Appunti)", "🔑 JWT Decoder (Da Appunti)",
        "🧪 Test RegEx Rapido...", "🧪 Test RegEx Rapido...",
        "📸 Copia Metadati (JSON)", "📸 Copia Metadati (JSON)",
        "🧬 Estrai Stringhe (Text)", "🧬 Estrai Stringhe (Text)",
        "🗜️ Aumenta Peso File (Pumper)...", "🗜️ Aumenta Peso File (Pumper)...",
        "🗑️ Distruzione Sicura", "🗑️ Distruzione Sicura",
        "🛠️ Sviluppatore & Sicurezza", "🛠️ Sviluppatore & Sicurezza",
        "🧩 Crea File da Appunti (Decodifica Base64)", "🧩 Crea File da Appunti (Decodifica Base64)",
        "🗜️ Crea File Dummy (Zero Fill)...", "🗜️ Crea File Dummy (Zero Fill)...",
        "🔗 Crea Symlink (Target da Appunti)", "🔗 Crea Symlink (Target da Appunti)",
        "🛠️ Sviluppatore", "🛠️ Sviluppatore",
        "⬇️ Git Pull", "⬇️ Git Pull",
        "✅ Git Add & Commit...", "✅ Git Add & Commit...",
        "📄 Crea File da Snippet...", "📄 Crea File da Snippet...",
        "Git Actions", "Git Actions",
        "💻 Programmazione", "💻 Programmazione",
        "📝 Incolla Appunti Veloci (.txt)", "📝 Incolla Appunti Veloci (.txt)",
        "⚙️ Esegui con Parametri", "⚙️ Esegui con Parametri",
        "⏱️ Aggiorna Data Modifica (Touch)", "⏱️ Aggiorna Data Modifica (Touch)",
        "🕰️ Modifica Attributi e Date...", "🕰️ Modifica Attributi e Date...",
        "✏️ Rinomina Elemento...", "✏️ Rinomina Elemento...",
        "🔗 Crea Collegamento...", "🔗 Crea Collegamento...",
        "🖥️ Apri in PowerShell", "🖥️ Apri in PowerShell",
        " Apri in VS Code", " Apri in VS Code",
        "🔧 Gestione & Azioni", "🔧 Gestione & Azioni",
        "🗃️ Rinomina Multipla...", "🗃️ Rinomina Multipla...",
        " Fast Merge (Unione Dati/Testi)", " Fast Merge (Unione Dati/Testi)",
        "🔗 Crea Collegamenti...", "🔗 Crea Collegamenti...",
        " Gestione & Azioni", " Gestione & Azioni",
        "🗜️ Comprimi in archivi separati (.zip)", "🗜️ Comprimi in archivi separati (.zip)",
        "🗜️ Comprimi in un unico archivio (.zip)", "🗜️ Comprimi in un unico archivio (.zip)",
        "📦 Super Zip", "📦 Super Zip",
        "Tutti in", "Tutti in",
        "Solo i .", "Solo i .",
        "Immagini", "Immagini",
        "Sviluppo", "Sviluppo",
        "Documenti", "Documenti",
        "Archivi", "Archivi",
        "🔍 Filtra e Copia Percorsi...", "🔍 Filtra e Copia Percorsi...",
        "📁 Filtra e Copia FILE reali...", "📁 Filtra e Copia FILE reali..."
    )
    
    ; --- ESPAÑOL ---
    LangMap["ES"] := Map(
        "TutTitle", "¡Bienvenido a FoxPath!",
        "TutSubtitle", "¡Tu nueva mascota está lista para ayudarte a gestionar archivos y rutas como un verdadero power-user!",
        "TutHowTo", "Cómo funciona",
        "TutHowToDesc", "Presiona el atajo  [ {1} ]  para invocar al zorro.`nSelecciona un archivo o carpeta en el Explorador de Archivos.",
        "TutInteract", "Interacción y Menú",
        "TutInteractDesc", "• Clic Izquierdo: Copia rápida al Portapapeles.`n• Clic Derecho: Accede a Acciones Rápidas, Extracción de Texto (OCR), Menú de Desarrollador y Filtros.",
        "TutCust", "Personalización",
        "TutCustDesc", "Haz clic en el engranaje (o elige la opción en el menú) para personalizar los atajos y la apariencia.",
        "TutOptStart", " Iniciar FoxPath automáticamente con Windows",
        "TutOptDesk", " Crear un acceso directo en el Escritorio",
        "TutBtnStart", "Comenzar a usar FoxPath ➔",
        "TutCopyright", "© 2026 Pedro Sanchez.`nTodos los derechos reservados.",
        "Lang", "Idioma",
        "SettingsTitle", "Ajustes de FoxPath",
        "TabAppearance", "🎨 Apariencia",
        "TabBehavior", "⚙️ Comportamiento",
        "TabTools", "🛠️ Herramientas",
        "VisualCust", "Personalización Visual",
        "Transp", "Transparencia ({1}/255):",
        "WinWidth", "Ancho de Ventana ({1}px):",
        "PanelHeight", "Altura Panel Info ({1}px):",
        "BtnColor", "Color de Botón:",
        "TxtColor", "Color de Texto:",
        "Palette", "Paleta",
        "InteractOpt", "Opciones de Interacción",
        "MultiSel", "Habilitar Selección Múltiple",
        "UnlockResize", "Desbloquear Redimensionamiento Manual",
        "PlaySound", "Reproducir Sonido al Copiar",
        "AutoHide", "Ocultar automáticamente al Zorro",
        "AutoStart", "Iniciar automáticamente con Windows",
        "GlobalShortcut", "Atajo de Teclado Global:",
        "PrimaryTool", "Herramienta Principal",
        "PrimaryAction", "Acción predeterminada al Clic Izquierdo:",
        "QuickMenu", "Menú Rápido (Clic Derecho)",
        "Slot", "Espacio {1}:",
        "SaveApply", "✔️ Guardar y Aplicar",
        "Reset", "🔄 Restablecer",
        "Info", "ℹ️ Acerca de FoxPath",
        "InfoMsg", "FoxPath v2.1.0`n`nTu asistente visual para la productividad en Windows.`n`n© 2026 Pedro Sanchez. Todos los derechos reservados.",
        "SettingsLang", "Idioma App:",
        "NoSel", "SIN SELECCIÓN",
        "Detected", "DETECTADO",
        "ClickFile", "clic en un archivo",
        
        "Nessuno", "Ninguno",
        "📋 ─── LIBRERIA COPIA E FORMATTAZIONE ───", "📋 ─── LIBRERÍA DE COPIA Y FORMATO ───",
        "Copia Percorso Normale", "Copiar Ruta Normal",
        "Copia come File Reali", "Copiar como Archivos Reales",
        "Copia tra Virgolette", "Copiar con Comillas",
        "Copia come Link Markdown", "Copiar como Enlace Markdown",
        "🖥️ ─── LIBRERIA PROGRAMMI E SISTEMA ───", "🖥️ ─── LIBRERÍA DE PROGRAMAS Y SISTEMA ───",
        "Apri in VS Code", "Abrir en VS Code",
        "Apri in PowerShell", "Abrir en PowerShell",
        "Rinomina Elemento", "Renombrar Elemento",
        "Formatta JSON", "Formatear JSON (Pretty Print)",
        "Minifica JSON", "Minificar JSON",
        "✍️ ─── LIBRERIA ESTRAZIONE E TESTO ───", "✍️ ─── LIBRERÍA DE EXTRACCIÓN Y TEXTO ───",
        "Copia Contenuto (Solo Testo)", "Copiar Contenido (Solo Texto)",
        "Copia Contenuto (Mantiene Formattazione)", "Copiar Contenido (Mantener Formato)",
        "Statistiche Testo", "Estadísticas de Texto",
        "Traduci in Google Translate", "Traducir en Google Translate",
        "Incolla Appunti Veloci", "Pegar Notas Rápidas",
        "📸 ─── LIBRERIA IMMAGINI E GRAFICA ───", "📸 ─── LIBRERÍA DE IMÁGENES Y GRÁFICOS ───",
        "Estrai Testo (OCR)", "Extraer Texto (OCR)",
        "Converti in PNG", "Convertir a PNG",
        "Converti in JPG", "Convertir a JPG",
        "Converti in BMP", "Convertir a BMP",
        "Estrai Palette Colori", "Extraer Paleta de Colores",
        "🛠️ ─── LIBRERIA UTILITÀ EXTRA ───", "🛠️ ─── LIBRERÍA DE UTILIDADES EXTRA ───",
        "Touch (Aggiorna Data)", "Touch (Actualizar Fecha)",
        "Distruzione Sicura", "Destrucción Segura",
        "Crea Collegamento", "Crear Acceso Directo",
        "Super Zip (Unico)", "Super Zip (Archivo Único)",
        "Super Zip (Separati)", "Super Zip (Archivos Separados)",
        "Svuota Cestino", "Vaciar Papelera",
        
        "Copia separati da Virgola", "Copiar separados por Coma",
        "Copia con Slash ( / )", "Copiar con Barra ( / )",
        "Copia Relativo (senza Unità)", "Copiar Relativo (sin Unidad)",
        "Formattazione Avanzata", "✨ Formato Avanzado",
        "Copia solo Nome File", "Copiar solo Nombre de Archivo",
        "Copia Cartella Padre", "Copiar Carpeta Padre",
        "Copia Contenuto del File", "📝 Copiar Contenido del Archivo",
        "Singolo File", "Archivo Único",
        "Azioni Rapide", "Acciones Rápidas",
        "Recenti (History)", "Recientes (Historial)",
        "Impostazioni", "⚙️ Ajustes...",
        "⚙️ Impostazioni...", "⚙️ Ajustes...",
        "Copia come Web URI (file:///)", "Copiar como Web URI (file:///)",
        "Copia come Array JSON", "Copiar como Array JSON",
        "Copia come Percorso WSL (/mnt/...)", "Copiar como Ruta WSL (/mnt/...)",
        "📝 Copia Contenuto (Solo Testo)", "📝 Copiar Contenido (Solo Texto)",
        "✨ Formatta JSON (Pretty Print)", "✨ Formatear JSON (Pretty Print)",
        "🗜️ Minifica JSON", "🗜️ Minificar JSON",
        "📄 Testo & Codice", "📄 Texto y Código",
        "📝 Copia Contenuto (Mantiene Formattazione)", "📝 Copiar Contenido (Mantener Formato)",
        "📝 Copia Contenuto (Solo Testo Grezzo)", "📝 Copiar Contenido (Solo Texto Sin Formato)",
        "📄 Esporta in PDF (Silenzioso)", "📄 Exportar a PDF (Silencioso)",
        "📄 Strumenti Office", "📄 Herramientas de Office",
        "🔍 Anteprima Dati (Head)", "🔍 Vista Previa de Datos (Head)",
        "🔄 Converti in JSON", "🔄 Convertir a JSON",
        "📊 Dati & File Log", "📊 Datos y Archivos Log",
        "📈 Statistiche Testo (Parole/Caratteri)", "📈 Estadísticas de Texto (Palabras/Caracteres)",
        "🌐 Traduci in Google Translate", "🌐 Traducir en Google Translate",
        "🔗 Copia come Link Markdown", "🔗 Copiar como Enlace Markdown",
        "✍️ Editoriale", "✍️ Editorial",
        "✂️ Copia SVG Minimizzato", "✂️ Copiar SVG Minificado",
        "🔍 Estrai Testo (OCR)", "🔍 Extraer Texto (OCR)",
        "📐 Ridimensiona (Smart Resize)...", "📐 Redimensionar (Smart Resize)...",
        "🖼️ Genera Icona (.ico)", "🖼️ Generar Icono (.ico)",
        "🔄 Converti in PNG", "🔄 Convertir a PNG",
        "🔄 Converti in JPG", "🔄 Convertir a JPG",
        "🔄 Converti in BMP", "🔄 Convertir a BMP",
        "🎨 Estrai Palette (Colori Dominanti)", "🎨 Extraer Paleta (Colores Dominantes)",
        "📸 Immagini & Grafica", "📸 Imágenes y Gráficos",
        "🔐 Calcola Checksum (MD5/SHA-256)", "🔐 Calcular Checksum (MD5/SHA-256)",
        "🌐 URL Encode / Decode...", "🌐 URL Encode / Decode...",
        "️ Copia come Base64", "️ Copiar como Base64",
        "🔑 JWT Decoder (Da Appunti)", "🔑 Decodificador JWT (Desde Portapapeles)",
        "🧪 Test RegEx Rapido...", "🧪 Prueba Rápida de RegEx...",
        "📸 Copia Metadati (JSON)", "📸 Copiar Metadatos (JSON)",
        "🧬 Estrai Stringhe (Text)", "🧬 Extraer Cadenas (Text)",
        "🗜️ Aumenta Peso File (Pumper)...", "🗜️ Aumentar Tamaño de Archivo (Pumper)...",
        "🗑️ Distruzione Sicura", "🗑️ Destrucción Segura",
        "🛠️ Sviluppatore & Sicurezza", "🛠️ Desarrollador y Seguridad",
        "🧩 Crea File da Appunti (Decodifica Base64)", "🧩 Crear Archivo desde Portapapeles (Decodificar Base64)",
        "🗜️ Crea File Dummy (Zero Fill)...", "🗜️ Crear Archivo Ficticio (Zero Fill)...",
        "🔗 Crea Symlink (Target da Appunti)", "🔗 Crear Symlink (Destino desde Portapapeles)",
        "🛠️ Sviluppatore", "🛠️ Desarrollador",
        "⬇️ Git Pull", "⬇️ Git Pull",
        "✅ Git Add & Commit...", "✅ Git Add y Commit...",
        "📄 Crea File da Snippet...", "📄 Crear Archivo desde Snippet...",
        "Git Actions", "Acciones de Git",
        "💻 Programmazione", "💻 Programación",
        "📝 Incolla Appunti Veloci (.txt)", "📝 Pegar Notas Rápidas (.txt)",
        "⚙️ Esegui con Parametri", "⚙️ Ejecutar con Parámetros",
        "⏱️ Aggiorna Data Modifica (Touch)", "⏱️ Actualizar Fecha de Modificación (Touch)",
        "🕰️ Modifica Attributi e Date...", "🕰️ Modificar Atributos y Fechas...",
        "✏️ Rinomina Elemento...", "✏️ Renombrar Elemento...",
        "🔗 Crea Collegamento...", "🔗 Crear Acceso Directo...",
        "🖥️ Apri in PowerShell", "🖥️ Abrir en PowerShell",
        " Apri in VS Code", " Abrir en VS Code",
        "🔧 Gestione & Azioni", "🔧 Gestión y Acciones",
        "🗃️ Rinomina Multipla...", "🗃️ Renombrado Masivo...",
        " Fast Merge (Unione Dati/Testi)", " Fast Merge (Unir Datos/Textos)",
        "🔗 Crea Collegamenti...", "🔗 Crear Accesos Directos...",
        " Gestione & Azioni", " Gestión y Acciones",
        "🗜️ Comprimi in archivi separati (.zip)", "🗜️ Comprimir en archivos separados (.zip)",
        "🗜️ Comprimi in un unico archivio (.zip)", "🗜️ Comprimir en un único archivo (.zip)",
        "📦 Super Zip", "📦 Super Zip",
        "Tutti in", "Todos en",
        "Solo i .", "Solo los .",
        "Immagini", "Imágenes",
        "Sviluppo", "Desarrollo",
        "Documenti", "Documentos",
        "Archivi", "Archivos",
        "🔍 Filtra e Copia Percorsi...", "🔍 Filtrar y Copiar Rutas...",
        "📁 Filtra e Copia FILE reali...", "📁 Filtrar y Copiar ARCHIVOS reales..."
    )
}

; Funzione Globale di Traduzione
Tr(key, params*) {
    Global SettingLang, LangMap
    if (!SettingLang || !LangMap.Has(SettingLang))
        SettingLang := "EN"
    
    if (LangMap[SettingLang].Has(key)) {
        text := LangMap[SettingLang][key]
        for i, param in params
            text := StrReplace(text, "{" i "}", param)
        return text
    }
    return key
}